local X = {};

X["Tableitem"] = 
{ "item_tango",
  "item_flask",
  "item_clarity",
  "item_tpscroll",
  "item_bottle",
  "item_arcane_boots",
  "item_power_treads",
  "item_medallion_of_courage",
  "item_mekansm",
  "item_armlet",
  "item_blade_mail",
  "item_shivas_guard",
  "item_mjollnir",
  "item_black_king_bar",
  "item_guardian_greaves",
  "item_solar_crest",
  "item_ghost",
  "item_glimmer_cape",
  "item_sheepstick",
  "item_ancient_janggo",
  "item_manta",
  "item_necronomicon",
  "item_helm_of_the_dominator",
  "item_ethereal_blade",
  "item_hand_of_midas",
  "item_satanic",
  "item_diffusal_blade",
  "item_lotus_orb",
  "item_mask_of_madness",
  "item_butterfly",
  "item_bloodthorn",
  "item_invis_sword",
  "item_silver_edge",
  "item_soul_ring",
  "item_bloodstone",
  "item_refresher",
  "item_veil_of_discord",
  "item_dagon",
  "item_cyclone",
  "item_pipe",
  "item_urn_of_shadows",
  "item_heavens_halberd",
  "item_abyssal_blade",
  "item_moon_shard",
  "item_hand_of_midas",
  "item_magic_stick"};


return X